import assert from 'node:assert/strict';
import { cpSync, existsSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import test from 'node:test';

import {
    buildAllLibraryIndexes,
    checkLibraryIndexes,
    writeLibraryIndexes,
} from '../scripts/build-library-indexes.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FIXTURE_FILES = [
    'data/raw/rawPresentationFormats.js',
    'data/raw/rawThematicCategories.js',
    'data/metadata/presentationIndexMetadata.json',
    'data/metadata/thematicIndexMetadata.json',
    'data/structured/presentationIndex.js',
    'data/structured/thematicIndex.js',
];

function createFixture() {
    const fixture = mkdtempSync(join(tmpdir(), 'rabbitmirror-library-builder-'));
    for (const relative of FIXTURE_FILES) {
        const target = join(fixture, relative);
        mkdirSync(dirname(target), { recursive: true });
        writeFileSync(target, readFileSync(join(ROOT, relative)));
    }
    return fixture;
}

function withFixture(run) {
    const fixture = createFixture();
    try {
        return run(fixture);
    } finally {
        rmSync(fixture, { recursive: true, force: true });
    }
}

function mutateText(root, relative, transform) {
    const file = join(root, relative);
    const before = readFileSync(file, 'utf8');
    const after = transform(before);
    assert.notEqual(after, before, `${relative} mutation must change the fixture`);
    writeFileSync(file, after, 'utf8');
}

function mutateJson(root, relative, transform) {
    const file = join(root, relative);
    const value = JSON.parse(readFileSync(file, 'utf8'));
    transform(value);
    writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function generatedByKind(results, kind) {
    return results.find(result => result.config.kind === kind);
}

test('current checked-in indexes are exactly the deterministic build output', () => {
    const first = checkLibraryIndexes(ROOT, { quiet: true });
    const second = buildAllLibraryIndexes(ROOT);
    assert.deepEqual(first.map(result => [result.config.kind, result.items.length]), [
        ['presentation', 208],
        ['theme', 165],
    ]);
    for (const result of first) {
        const repeated = generatedByKind(second, result.config.kind);
        assert.equal(result.changed, false, `${result.config.kind} index must be current`);
        assert.equal(result.generatedSource, result.currentSource, `${result.config.kind} generated bytes must equal checked-in bytes`);
        assert.equal(repeated.generatedSource, result.generatedSource, `${result.config.kind} builds must be byte-deterministic`);
    }
});

test('write mode updates only the selected mother entry and check mode then passes', () => withFixture(root => {
    mutateText(root, 'data/raw/rawPresentationFormats.js', source => source.replace(
        '角色自制榜等，题材与风格不限。',
        '角色自制榜等，题材、风格与媒介不限。',
    ));
    assert.throws(() => checkLibraryIndexes(root, { quiet: true }), /generated indexes are stale/);
    const written = writeLibraryIndexes(root, { quiet: true });
    assert.deepEqual(written.changed.map(result => result.config.kind), ['presentation']);
    checkLibraryIndexes(root, { quiet: true });
    const presentation = generatedByKind(buildAllLibraryIndexes(root), 'presentation');
    const ranking = presentation.items.find(item => item.id === '1.3.4');
    assert.match(ranking.summary, /题材、风格与媒介不限/);
    assert.match(ranking.raw, /题材、风格与媒介不限/);
}));

test('new mother entries fail closed until matching metadata is deliberately added', () => withFixture(root => {
    mutateText(root, 'data/raw/rawPresentationFormats.js', source => source.replace(
        '\n`;\n',
        '\n  * **99.99 Builder Test**：仅用于构建器回归。\n`;\n',
    ));
    assert.throws(() => buildAllLibraryIndexes(root), /mother entries 209 != metadata entries 208/);
}));

test('missing, duplicated or reordered metadata cannot silently remap mother entries', () => {
    withFixture(root => {
        mutateJson(root, 'data/metadata/presentationIndexMetadata.json', metadata => metadata.entries.pop());
        assert.throws(() => buildAllLibraryIndexes(root), /mother entries 208 != metadata entries 207/);
    });
    withFixture(root => {
        mutateJson(root, 'data/metadata/presentationIndexMetadata.json', metadata => {
            metadata.entries[1].id = metadata.entries[0].id;
        });
        assert.throws(() => buildAllLibraryIndexes(root), /duplicate metadata id/);
    });
    withFixture(root => {
        mutateJson(root, 'data/metadata/presentationIndexMetadata.json', metadata => {
            [metadata.entries[0], metadata.entries[1]] = [metadata.entries[1], metadata.entries[0]];
        });
        assert.throws(() => buildAllLibraryIndexes(root), /raw order\/source mismatch/);
    });
});

test('renaming a mother item requires preserving the previous title as an alias', () => {
    withFixture(root => {
        mutateText(root, 'data/raw/rawPresentationFormats.js', source => source.replace(
            '**1.3.4 排行榜**',
            '**1.3.4 排行总榜**',
        ));
        assert.throws(() => buildAllLibraryIndexes(root), /title changed from "排行榜" to "排行总榜"/);
    });
    withFixture(root => {
        mutateText(root, 'data/raw/rawPresentationFormats.js', source => source.replace(
            '**1.3.4 排行榜**',
            '**1.3.4 排行总榜**',
        ));
        mutateJson(root, 'data/metadata/presentationIndexMetadata.json', metadata => {
            metadata.entries.find(entry => entry.id === '1.3.4').aliases = ['排行榜'];
        });
        writeLibraryIndexes(root, { quiet: true });
        const item = generatedByKind(buildAllLibraryIndexes(root), 'presentation').items.find(entry => entry.id === '1.3.4');
        assert.equal(item.title, '排行总榜');
        assert.deepEqual(item.aliases, ['排行榜']);
    });
});

test('curated compact summaries remain metadata overrides while raw pointers follow the mother library', () => withFixture(root => {
    const metadata = JSON.parse(readFileSync(join(root, 'data/metadata/thematicIndexMetadata.json'), 'utf8'));
    const override = metadata.entries.find(entry => entry.id === 'B.3.3').summaryOverride;
    mutateText(root, 'data/raw/rawThematicCategories.js', source => source.replace(
        '结束时不要和解，让痛楚悬在字里行间。',
        '结束时不要和解，让痛楚继续悬在字里行间。',
    ));
    const item = generatedByKind(buildAllLibraryIndexes(root), 'theme').items.find(entry => entry.id === 'B.3.3');
    assert.equal(item.summary, override);
    assert.match(item.raw, /继续悬在字里行间/);
}));

test('unknown metadata fields and wrong source declarations fail closed', () => {
    withFixture(root => {
        mutateJson(root, 'data/metadata/presentationIndexMetadata.json', metadata => {
            metadata.entries[0].accidentalField = true;
        });
        assert.throws(() => buildAllLibraryIndexes(root), /unknown keys: accidentalField/);
    });
    withFixture(root => {
        mutateJson(root, 'data/metadata/presentationIndexMetadata.json', metadata => {
            metadata.source = 'data/raw/wrong.js';
        });
        assert.throws(() => buildAllLibraryIndexes(root), /source must be data\/raw\/rawPresentationFormats\.js/);
    });
});

test('a hand-edited generated index is rejected instead of becoming a second source of truth', () => withFixture(root => {
    mutateText(root, 'data/structured/presentationIndex.js', source => source.replace(
        '"title": "排行榜"',
        '"title": "手工改坏的排行榜"',
    ));
    assert.throws(() => checkLibraryIndexes(root, { quiet: true }), /generated indexes are stale|title changed from/);
}));

test('the verified packager rebuilds and checks indexes before creating the ZIP', () => {
    const source = readFileSync(join(ROOT, 'scripts/package-candidate.mjs'), 'utf8');
    const writeAt = source.indexOf('writeLibraryIndexes(root)');
    const checkAt = source.indexOf('checkLibraryIndexes(root)', writeAt);
    const testsAt = source.indexOf('runTests(root)', checkAt);
    const zipAt = source.indexOf("'create'", testsAt);
    const extractedCheckAt = source.indexOf('checkLibraryIndexes(extractedRoot)', zipAt);
    assert.ok(writeAt >= 0 && writeAt < checkAt, 'packaging must rebuild before checking');
    assert.ok(checkAt < testsAt, 'index check must precede source tests');
    assert.ok(testsAt < zipAt, 'tests must pass before ZIP creation');
    assert.ok(zipAt < extractedCheckAt, 'the exact extracted ZIP must be checked again');
});

test('validation failures never partially overwrite either generated index', () => withFixture(root => {
    const presentationPath = join(root, 'data/structured/presentationIndex.js');
    const themePath = join(root, 'data/structured/thematicIndex.js');
    const presentationBefore = readFileSync(presentationPath, 'utf8');
    const themeBefore = readFileSync(themePath, 'utf8');

    mutateText(root, 'data/raw/rawPresentationFormats.js', source => source.replace(
        '角色自制榜等，题材与风格不限。',
        '角色自制榜等，题材与风格、媒介不限。',
    ));
    mutateJson(root, 'data/metadata/thematicIndexMetadata.json', metadata => {
        metadata.entries[0].unknownBuildField = 'reject-me';
    });

    assert.throws(() => writeLibraryIndexes(root, { quiet: true }), /unknown keys: unknownBuildField/);
    assert.equal(readFileSync(presentationPath, 'utf8'), presentationBefore, 'presentation index must remain untouched when theme validation fails');
    assert.equal(readFileSync(themePath, 'utf8'), themeBefore, 'theme index must remain untouched when validation fails');
}));


test('plain multiline continuations fail closed in both mother libraries with source context', () => {
    withFixture(root => {
        mutateText(root, 'data/raw/rawPresentationFormats.js', source => source.replace(
            '* **6.2.5 修仙养成**：高自由度修仙养成游戏，可自由探索、修炼、结缘、攻略不同人物并触发大量随机事件与关系变化；允许「海王」式多线发展。',
            '* **6.2.5 修仙养成**：高自由度修仙养成游戏，可自由探索、修炼、结缘、攻略不同人物并触发大量随机事件与关系变化；允许「海王」式多线发展。\n    第二行继续说明，绝不能被静默丢弃。',
        ));
        assert.throws(
            () => checkLibraryIndexes(root, { quiet: true }),
            error => /data\/raw\/rawPresentationFormats\.js:\d+: unsupported non-empty mother-library line/.test(String(error?.message || error))
                && /after 6\.2\.5 修仙养成/.test(String(error?.message || error))
                && /must remain on one line/.test(String(error?.message || error)),
        );
    });

    withFixture(root => {
        mutateText(root, 'data/raw/rawThematicCategories.js', source => source.replace(
            '- **C.1.6 许愿柳**: 本质上是一个可以实现愿望的道具，但实现方式往往出人意料，甚至带来恐怖后果。',
            '- **C.1.6 许愿柳**: 本质上是一个可以实现愿望的道具，但实现方式往往出人意料，甚至带来恐怖后果。\n    第二行继续说明，绝不能被静默丢弃。',
        ));
        assert.throws(
            () => checkLibraryIndexes(root, { quiet: true }),
            error => /data\/raw\/rawThematicCategories\.js:\d+: unsupported non-empty mother-library line/.test(String(error?.message || error))
                && /after C\.1\.6 许愿柳/.test(String(error?.message || error))
                && /must remain on one line/.test(String(error?.message || error)),
        );
    });
});

test('multiline validation fails before write mode can touch either generated index', () => withFixture(root => {
    const presentationPath = join(root, 'data/structured/presentationIndex.js');
    const themePath = join(root, 'data/structured/thematicIndex.js');
    const presentationBefore = readFileSync(presentationPath, 'utf8');
    const themeBefore = readFileSync(themePath, 'utf8');

    mutateText(root, 'data/raw/rawPresentationFormats.js', source => source.replace(
        '* **6.2.5 修仙养成**：高自由度修仙养成游戏，可自由探索、修炼、结缘、攻略不同人物并触发大量随机事件与关系变化；允许「海王」式多线发展。',
        '* **6.2.5 修仙养成**：高自由度修仙养成游戏，可自由探索、修炼、结缘、攻略不同人物并触发大量随机事件与关系变化；允许「海王」式多线发展。\n    第二行继续说明，绝不能被静默丢弃。',
    ));

    assert.throws(() => writeLibraryIndexes(root, { quiet: true }), /must remain on one line/);
    assert.equal(readFileSync(presentationPath, 'utf8'), presentationBefore, 'presentation index must remain untouched');
    assert.equal(readFileSync(themePath, 'utf8'), themeBefore, 'theme index must remain untouched');
    assert.deepEqual(
        readdirSync(join(root, 'data/structured')).filter(name => name.includes('.tmp-')),
        [],
        'validation failure must not leave temporary index files',
    );
}));

test('existing explicit raw-only auxiliary bullets remain valid while plain continuations are rejected', () => {
    const raw = readFileSync(join(ROOT, 'data/raw/rawPresentationFormats.js'), 'utf8');
    assert.match(raw, /^\s+\* 落地时必须实际呈现 ADV/m);
    assert.match(raw, /^\s+\* 光点颜色解码表/m);
    checkLibraryIndexes(ROOT, { quiet: true });
});

test('candidate packaging stops before ZIP creation when a mother entry gains a plain continuation', () => {
    const sandbox = mkdtempSync(join(tmpdir(), 'rabbitmirror-library-package-guard-'));
    const root = join(sandbox, 'tototest-main');
    const output = join(sandbox, 'should-not-exist.zip');
    try {
        cpSync(ROOT, root, { recursive: true });
        mutateText(root, 'data/raw/rawPresentationFormats.js', source => source.replace(
            '* **6.2.5 修仙养成**：高自由度修仙养成游戏，可自由探索、修炼、结缘、攻略不同人物并触发大量随机事件与关系变化；允许「海王」式多线发展。',
            '* **6.2.5 修仙养成**：高自由度修仙养成游戏，可自由探索、修炼、结缘、攻略不同人物并触发大量随机事件与关系变化；允许「海王」式多线发展。\n    第二行继续说明，绝不能被静默丢弃。',
        ));
        const result = spawnSync(process.execPath, [
            'scripts/package-candidate.mjs',
            '--root', root,
            '--output', output,
        ], {
            cwd: root,
            encoding: 'utf8',
            maxBuffer: 16 * 1024 * 1024,
        });
        assert.notEqual(result.status, 0, 'packaging must fail closed');
        assert.match(`${result.stdout || ''}${result.stderr || ''}`, /must remain on one line/);
        assert.equal(existsSync(output), false, 'invalid mother library must not produce a ZIP');
    } finally {
        rmSync(sandbox, { recursive: true, force: true });
    }
});

test('build tooling is not imported by the browser runtime graph', () => {
    const runtimeFiles = [join(ROOT, 'index.js')];
    const visit = current => {
        for (const entry of readdirSync(current, { withFileTypes: true })) {
            const full = join(current, entry.name);
            if (entry.isDirectory()) visit(full);
            else if (/\.m?js$/.test(entry.name)) runtimeFiles.push(full);
        }
    };
    visit(join(ROOT, 'src'));
    visit(join(ROOT, 'data'));

    for (const file of runtimeFiles) {
        const source = readFileSync(file, 'utf8');
        assert.doesNotMatch(source, /build-library-indexes|package-candidate|create-extension-zip/, `${file} must not load build-only tooling at runtime`);
    }
});
